# Generated by Django 3.1.7 on 2021-03-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210318_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='industry',
        ),
    ]
